### ISSUE TITLE
Always loaded while saving

### ISSUE THREAD

**Issue by imyzt** [yimou6/secret#2]
version: latest  
system: win64   
Language: zh-cn  

新版本覆盖安装的, 在保存的时候, 都会出现这种情况. 查看了data.db文件,发现有写写内容, 但是还是不能够展示在页面, 一直处于加载中状态. 见下图  

![](http://ww1.sinaimg.cn/large/005SWfHCgy1g0m55b7hejj30m80goq2x.jpg)

**Comment by yimou6** [comment]
已解决
